name: Generating Sphinx Docs

on:
  push:
    branches:
      - main
      - development
      - dev
      - workflow/docgen

# Set the Job
jobs:
  docgen:
    # Name the Job
    name: Automated Document Generation
    # Set environment
    runs-on: ubuntu-latest

    # Load all steps
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2
      # Python 3.8 Setup
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      # Install dependencies
      - run: pip install -r requirements.txt
      # Generate Docs
      - name: Generate Docs
        working-directory: ./docs
        run: |
          make html
          make markdown
      # Create Pull Request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SPHINXDOCGEN }}
          commit-message: Update Doc
          base : ${{ github.head_ref }}
          delete-branch: false
          title: 'updated docs'
          body: |
            This Pull Request is auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
      # Automatic Merge
      #- name: Enable Pull Request Automerge
      #  if: steps.cpr.outputs.pull-request-operation == 'created'
      #  uses: peter-evans/enable-pull-request-automerge@v1
      #  with:
      #    token: ${{ secrets.SPHINXDOCGEN }}
      #    pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      #    merge-method: squash